### ISSUE TITLE
Deprecated NodeJS Version 8 for lambdas

### ISSUE THREAD

**Issue by gvasquez95** [foby/aws-ecs-public-dns#2]
AWS suggests using nodejs12.x, I'm trying your project as-is with just that slight change

**Comment by foby** [comment]
Yeah good point. It's been a while. Feel free to file a pull request.

**Comment by gvasquez95** [comment]
already tested with version 12x and worked flawlessly, so I'll go for the PR

**Comment by gvasquez95** [comment]
I just created the PR with a few minor other improvements, but now realized it's to your `develop` branch as it's your default, not `master`. Is that right?

**Comment by foby** [comment]
Correct, develop is default. Thanks for contributing.
